### PR TITLE
deps: less precise versions to avoid dep bots updating patch versions

### PR DESCRIPTION
**Pull request by poliorcetics**
See https://github.com/HarfangLab/endpoint-sec/pull/7/files#r1280891213 for an instance of the problem

### CODE REVIEW

**Review by roblabla — APPROVED** [review]
LGTM. It does mean, however, that if we ever need something like "version 0.2.3 or semver-compatible", we cannot easily express that.

**Comment by poliorcetics** [comment]
Maybe there is a way to tell dependabot to only update on breaking changes ?

**Comment by poliorcetics** [comment]
but then `2.x` would still be updated to`2.x+1`

**Comment by roblabla** [comment]
yeah, there's no good solution that's going to cover every case (short of fixing https://github.com/renovatebot/renovate/issues/22820 and switching to renovate 😄 )

Honestly, I think the change proposed in this MR works well enough for now, so we can go with that, and if we ever need something more complicated later, we can figure out what to do then.

**Pull request merged**
